## 更新日期: 2023-05-21
# 脚本仓库配置
# 官网教程：https://arcadia.cool/docs/configuration/script/repo/config
repo:
  - name: "" # 仓库名称
    url: "" # 仓库远程地址
    branch: "" # 分支名称
    enable: true # 是否启用该仓库配置
    cronSettings:
      updateTaskList: false # 是否为该配置启用定时任务（默认不启用）
      scriptsPath: '' # 定时脚本路径（默认为仓库根目录）
      scriptsType: # 定时脚本文件格式（默认为 JavaScript、Python、TypeScript 脚本）
        - js
        - ts
        - py
      whiteList: '' # 定时脚本匹配白名单（默认为空，即所有脚本）
      blackList: '' # 定时脚本匹配黑名单（默认为空）
      autoDisable: false # 是否自动禁用新的定时任务
      addNotify: true # 是否为新增定时任务推送通知提醒
      delNotify: true # 是否为过期定时任务推送通知提醒

# 远程脚本配置
# 官网教程：https://arcadia.cool/docs/configuration/script/raw/config
raw:
  - name: "" # 脚本名称
    url: "" # 脚本远程地址
    cronSettings:
      updateTaskList: false # 是否为该脚本启用定时任务

# 全局配置
gobal:
  autoDisableRepoDuplicateCron: true # 自动禁用来自脚本仓库的重复定时任务
  rawDependencyFilter: "" # 远程脚本依赖文件过滤（白名单）
