name: Repo_Sync_with_Key
on:
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y && apt-get install -y build-essential git git-core curl wget && apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - name: Clone stable
      run: |
        git clone -b stable git@gitee.com:supermanito/jd_base.git stable
    - name: Push stable
      uses: ad-m/github-push-action@master
      with:
        directory: stable
        github_token: ${{ secrets.TOKEN }}
        branch: stable
    - name: Clone main
      run: |
        git clone -b master git@gitee.com:supermanito/jd_base.git jd_base
    - name: Push jd_base
      uses: ad-m/github-push-action@master
      with:
        directory: jd_base
        github_token: ${{ secrets.TOKEN }}
        branch: jd_base
    - name: Clone Dev
      run: |
        git clone -b dev git@gitee.com:supermanito/jd_base.git jd_base_dev
    - name: Push Dev
      uses: ad-m/github-push-action@master
      with:
        directory: jd_base_dev
        github_token: ${{ secrets.TOKEN }}
        branch: jd_base_dev
    - name: Clone dev.githubwyj
      run: |
        git clone -b dev.githubwyj git@gitee.com:supermanito/jd_base.git jd_base_dev.githubwyj
    - name: Push jd_base_dev.githubwyj
      uses: ad-m/github-push-action@master
      with:
        directory: jd_base_dev.githubwyj
        github_token: ${{ secrets.TOKEN }}
        branch: jd_base_dev.githubwyj
    - name: Clone jd_base_main
      run: |
        git clone -b main git@gitee.com:supermanito/jd_base.git jd_base_main
    - name: Push jd_base_main
      uses: ad-m/github-push-action@master
      with:
        directory: jd_base_main
        github_token: ${{ secrets.TOKEN }}
        branch: jd_base_main
    - name: Clone panel_sign_json
      run: |
        git clone -b master git@gitee.com:supermanito/panel_sign_json.git panel_sign_json
    - name: Push panel_sign_json
      uses: ad-m/github-push-action@master
      with:
        directory: panel_sign_json
        github_token: ${{ secrets.TOKEN }}
        branch: panel_sign_json
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.TOKEN }}
        retain_days: 1
        keep_minimum_runs: 2
